name: COBOL Check Automation
on:
  push:
    branches: [ main ]
jobs:
  cobol-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Install Zowe CLI
      run: npm install -g @zowe/cli@latest
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Setup Mainframe Environment and Upload COBOL check
      env:
        ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
      run: |
        # Here we'll add our commands to run cobolcheck
        echo "Running COBOL Check"
        # Add actual cobolcheck commands here
        chmod +x .github/scripts/zowe_operations.sh
        .github/scripts/zowe_operations.sh
    - name: Run COBOL Check on Mainframe
      env:
        ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
      run: |
        chmod +x .github/scripts/mainframe_operations.sh
        .github/scripts/mainframe_operations.sh
